# -*- coding: utf-8 -*-
"""prevendo_covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bj05IDtb1E41mwPlH90-kZgtG5bB71pq

#PREVISAO SOBRE COVID

BIBLIOTECAS
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
import seaborn as sns

covid = pd.read_csv('arquivos/covid_19_data.csv')
covid.shape

covid.head()

df_brasil = covid[covid['Country/Region'] == 'Brazil']
df_brasil.shape

df_brasil.head(21)

sns.lineplot(df_brasil['ObservationDate'], df_brasil['Confirmed'])

df_sum = covid.groupby('ObservationDate').agg({'Confirmed': 'sum', 'Deaths': 'sum','Recovered':'sum'}).reset_index()

df_sum.head()

df_sum.tail()

plt.stackplot(df_sum['ObservationDate'], [df_sum['Confirmed'], df_sum['Deaths'], df_sum['Recovered']],
              labels = ['Confirmados', 'Mortes', 'Recuperados'])
plt.legend(loc = 'upper left')

sns.pairplot(covid)

